Event.Add("ResourceStart", function(name)
	Local.UnlockAbility(Ability.GrapplingHook)
	Local.UnlockAbility(Ability.Parachute)
	Local.UnlockAbility(Ability.Wingsuit)
	Local.UnlockAbility(Ability.Hammer)
	Local.UnlockAbility(Ability.ExitVehicle)
	Local.UnlockAbility(Ability.Tether)
	Local.UnlockAbility(Ability.RetractTether)
	Local.UnlockAbility(Ability.ParachuteSlingshot)
end)